#include "net_device_tree_relation_kinergy_ii.h"
#include "net_device_id_kinergy_ii.h"
#include "net_system_info_list.h"



#define cb_device_tree_layers_number                77


const net_device_tree_element_info st_net_device_tree_relation_kinergy_ii[cb_device_tree_layers_number] =
{
	{
		&dwa_device_id_kinergy_ii[cw_device_id_index_system],
		{
			1,
			{
				&dwa_device_id_kinergy_ii[cw_device_id_index_kinergy_ii],
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_kinergy_ii],
		{
			9,
			{
                &dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_u1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_u2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_u3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_v1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_v2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_v3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_w1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_w2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_w3],
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_u1],
		{
			10,
			{
                &dwa_device_id_kinergy_ii[cw_device_id_index_meter_1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_u1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u1_0],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u1_1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u1_2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u1_3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u1_4],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u1_5],
                &dwa_device_id_kinergy_ii[cw_device_id_index_pv_1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_pv_2],
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_u1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u1_0],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u1_1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u1_2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u1_3],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u1_4],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u1_5],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_u2],
		{
			7,
			{
                &dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_u2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u2_0],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u2_1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u2_2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u2_3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u2_4],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u2_5],
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_u2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u2_0],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u2_1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u2_2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u2_3],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u2_4],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u2_5],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_u3],
		{
			7,
			{
                &dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_u3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u3_0],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u3_1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u3_2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u3_3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u3_4],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u3_5],
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_u3],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u3_0],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u3_1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u3_2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u3_3],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u3_4],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_u3_5],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_v1],
		{
			7,
			{
                &dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_v1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v1_0],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v1_1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v1_2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v1_3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v1_4],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v1_5],
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_v1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v1_0],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v1_1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v1_2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v1_3],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v1_4],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v1_5],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_v2],
		{
			7,
			{
                &dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_v2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v2_0],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v2_1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v2_2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v2_3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v2_4],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v2_5],
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_v2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v2_0],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v2_1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v2_2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v2_3],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v2_4],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v2_5],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_v3],
		{
			7,
			{
                &dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_v3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v3_0],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v3_1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v3_2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v3_3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v3_4],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v3_5],
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_v3],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v3_0],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v3_1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v3_2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v3_3],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v3_4],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_v3_5],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_w1],
		{
			7,
			{
                &dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_w1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w1_0],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w1_1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w1_2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w1_3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w1_4],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w1_5],
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_w1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w1_0],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w1_1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w1_2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w1_3],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w1_4],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w1_5],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_w2],
		{
			7,
			{
                &dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_w2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w2_0],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w2_1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w2_2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w2_3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w2_4],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w2_5],
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_w2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w2_0],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w2_1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w2_2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w2_3],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w2_4],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w2_5],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_cklcd_w3],
		{
			7,
			{
                &dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_w3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w3_0],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w3_1],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w3_2],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w3_3],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w3_4],
                &dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w3_5],
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_ck_inverter_w3],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w3_0],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w3_1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w3_2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w3_3],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w3_4],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_mppt_w3_5],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_pv_1],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_pv_2],
		{
			0,
			{
                0,
			},
		}
	},
    {
		&dwa_device_id_kinergy_ii[cw_device_id_index_meter_1],
		{
			0,
			{
                0,
			},
		}
	},
};

const net_device_tree_element_info_list st_net_device_tree_element_info_list_kinergy_ii =
{
    cb_device_tree_layers_number,
    (net_device_tree_element_info *)&st_net_device_tree_relation_kinergy_ii[0],
};
